version: 2

sources:
    - name: raw_staging
      database: PILOT
      schema: RAW_STAGE
      tables:
        - name: calpro_staging_calpronps
        - name: seed_locations
        - name: vetspire_stage_locations

