version: 2

sources:
    - name: raw_staging
      database: PILOT
      schema: RAW_STAGE
      tables:
        - name: calpro_staging_calpronps
        - name: seed_locations
        - name: vetspire_stg_locations
        - name: vetspire_stg_providers
        - name: paycom_employee_extra_data
        - name: paycom_stg_employees
        - name: vetspire_stg_clients

